apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "data-warehouse-storage"
spec:
  defaults:
    templates:
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
  configuration:
    clusters:
      - name: "dw-storage"
        layout:
          shardsCount: 1
          replicasCount: 1
  reconciling:
    policy: "nowait"
    configMapPropagationTimeout: 90
    cleanup:
      unknownObjects:
        statefulSet: Delete
        pvc: Delete
        configMap: Delete
        service: Delete
      reconcileFailedObjects:
        statefulSet: Retain
        pvc: Retain
        configMap: Retain
        service: Retain
  templates:
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
      - name: log-volume-template
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
---
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"

metadata:
  name: "data-warehouse"

spec:
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeepers.zoo1ns
    clusters:
      - name: dw-master
        layout:
          replicasCount: 2
      - name: dw-worker
        zookeeper:
          nodes:
            - host: zookeeper-0.zookeepers
            - host: zookeeper-1.zookeepers
            - host: zookeeper-2.zookeepers
        layout:
          replicasCount: 2
---