apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "data-warehouse"
spec:

# .spec.defaults
  defaults:
    distributedDDL:
      profile: default
    templates:
      podTemplate: clickhouse-v22.2
      dataVolumeClaimTemplate: data-volume-template
      logVolumeClaimTemplate: log-volume-template
    replicasUseFQDN: "no"
# .spec.configuration
  configuration:
    zookeeper:
      nodes:
        - host: zookeeper-0.zookeeper-headless.default.svc.cluster.local
        - host: zookeeper-1.zookeeper-headless.default.svc.cluster.local
        - host: zookeeper-2.zookeeper-headless.default.svc.cluster.local

# .spec.configuration.clusters
    clusters:
      - name: cluster
        templates:
          dataVolumeClaimTemplate: data-volume-template
          logVolumeClaimTemplate: log-volume-template
        layout:
          replicasCount: 2
          shardsCount: 3

# .spec.reconciling
  reconciling:
    policy: "nowait"
    configMapPropagationTimeout: 90
    cleanup:
      unknownObjects:
        statefulSet: Delete
        pvc: Delete
        configMap: Delete
        service: Delete
      reconcileFailedObjects:
        statefulSet: Retain
        pvc: Retain
        configMap: Retain
        service: Retain

# .spec.templates
  templates:
  
    # .spec.templates.volumeClaimtemplates
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
      - name: log-volume-template
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
      - name: default-volume-claim
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    
    # .spec.templates.podTemplates
    podTemplates:
      # pod template for ClickHouse v22.2
      - name: clickhouse-v22.2
        # type PodSpec struct {} from k8s.io/core/v1
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.2
              volumeMounts:
                - name: default-volume-claim
                  mountPath: /var/lib/clickhouse
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "100m"
                limits:
                  memory: "64Mi"
                  cpu: "100m"
---